config/routes.rb
Rails.application.routes.draw do
  root 'orders#index'
  resources :orders, only: %i[new create edit update destroy]
  resources :order_product, only: %i[edit update create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true, length: { in: 4..24 }, uniqueness: true
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  validates :units, presence: true, numericality: { greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  validates_with MinimumPriceValidator
  validates_with MultipleUnitValidator

  belongs_to :order
  belongs_to :product

  def great_sale?
    unit_price > product.price
  end

  def unit_price=(raw)
    super(raw.to_s.gsub(',', '').to_f.round(2))
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  validates :multiple, presence: true
  has_many :order_products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/order_product_controller.rb
class OrderProductController < ApplicationController
  def edit
    @order_product = OrderProduct.find(params[:id])
  end

  def update
    @order_product = OrderProduct.find(params[:id])
    return redirect_to(edit_order_path(@order_product.order)) if @order_product.update(update_params)
    flash[:warning] = @order_product.errors.to_a.first
    render :edit
  end

  def create
    flash[:warning] = order_error unless order_product.valid? && order_product.save
    redirect_to(edit_order_path(order))
  end

  def destroy
    OrderProduct.find(params[:id]).destroy!
    redirect_to(edit_order_path(order))
  end

  private

  def update_params
    params[:order_product].permit(:units, :unit_price, :product_id)
  end

  def order_error
    order_product.errors.to_a.first
  end

  def order_product
    @order_product ||= OrderProduct.new(
      order: order,
      product: product,
      units: params[:order_product][:units],
      unit_price: params[:order_product][:unit_price]
    )
  end

  def order
    @order ||= Order.find(params[:order_id])
  end

  def product
    @product ||= Product.find(params[:order_product][:product_id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :orders, only: :index
  before_action :order, only: :edit

  def index; end

  def new
    @new_order = Order.new
  end

  def create
    return redirect_to(root_path) if new_order.valid? && new_order.save
    flash[:warning] = new_roder.errors.to_a.first

    render :new
  end

  def edit
    @order_product = OrderProduct.new(order: order)
  end

  def update
    order.customer = customer
    return redirect_to(root_path) if order.valid? && order.save
    flash[:warning] = order.errors.to_a.first

    render :edit
  end

  def destroy
    flash[:success] = I18n.t('.destroyed') if order.destroy
    redirect_to(root_path)
  end

  private

  def order
    @order ||= Order.find(params[:id])
  end

  def new_order
    @new_order ||= Order.new(customer: customer)
  end

  def orders
    @orders ||= Order.all.includes(:customer, :order_products)
  end

  def customer
    @customer ||= Customer.find(params[:order][:customer_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chewie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary">
      <%= link_to 'Chewie Store', root_path, class: 'navbar-brand mx-md-auto' %>
    </nav>

    <main class="container mt-3">
      <%= render('shared/flash') %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/order_product/edit.html.erb
<div class="row">
  <div class="col-10">
    <h2>
      <%= t('.title') %>
    </h2>
  </div>
  <div class="col-2">
    <%= link_to edit_order_path(id: @order_product.order_id), class: 'btn btn-outline-primary' do %>
      <%= t('.back') %>
    <% end %>
  </div>
</div>

<hr class="line">

<%= form_for @order_product, url: order_product_path(@order_product), method: :patch do |f| %>
  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :product, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.select :product_id, Product.order(:name).collect { |p| [ p.name, p.id ] }, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :units, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.number_field :units, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :unit_price, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.text_field :unit_price, step: :any, class: 'form-control js-currency' %>
    </div>
  </div>

  <div class="col-12 text-center">
    <%= f.submit t('.save') %>
  </div>
<% end %>

app/views/orders/_form.html.erb
<div class="form-group row">
  <div class="col-6 text-right font-weight-bold">
    <%= f.label :customer, html: {class: 'col-sm-2 col-form-label'} %>
  </div>
  <div class="col-6">
    <%= f.select :customer_id, Customer.order(:name).collect { |p| [ p.name, p.id ] }, html: {class: 'form-control'}%>
  </div>
</div>

app/views/orders/_order.html.erb
<tr id="<%= "order#{order.id}" %>">
  <th class="align-middle" scope="row"><%= order.id %></th>
  <td class="align-middle"><%= order.customer.name %></td>
  <td class="align-middle"><%= order.order_products.count %></td>
  <td class="align-middle">
    <%= link_to edit_order_path(order), class: 'btn btn-outline-primary', order: @order do %>
      <%= fa_icon('pencil') %>
    <% end %>
    <%= link_to order_path(order), class: 'btn btn-outline-danger', method: :delete do %>
      <%= fa_icon('trash') %>
    <% end %>
  </td>
</tr>

app/views/orders/_order_product.html.erb
<tr id="<%= "order#{order_product.id}" %>">
  <td class="align-middle">
    <% if order_product.great_sale? %>
      <div class="btn btn-outline-success" data-toggle="tooltip" data-placement="left" title="<%= t('.great_sale') %>">
        <%= fa_icon('smile-o') %>
      </div>
    <% else %>
      <div class="btn btn-outline-warning" data-toggle="tooltip" data-placement="left" title="<%= t('.not_great_sale') %>">
        <%= fa_icon('frown-o') %>
      </div>
    <% end %>
  </td>
  <td class="align-middle"><%= order_product.product.name %></td>
  <td class="align-middle"><%= order_product.units %></td>
  <td class="align-middle"><%= number_to_currency(order_product.unit_price) %></td>
  <td class="align-middle">
    <%= link_to edit_order_product_path(order_product), class: 'btn btn-outline-primary' do %>
      <%= fa_icon('pencil') %>
    <% end %>
    <%= link_to order_product_path(order_product, order_id: @order.id), class: 'btn btn-outline-danger', method: :delete do %>
      <%= fa_icon('trash') %>
    <% end %>
  </td>
</tr>

app/views/orders/_order_product_form.html.erb
<%= form_for @order_product, url: order_product_index_path(order_id: order), method: :post do |f| %>
  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :product, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.select :product_id, Product.order(:name).collect { |p| [ p.name, p.id ] }, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :units, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.number_field :units, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-6 text-right font-weight-bold">
      <%= f.label :unit_price, class: 'col-form-label' %>
    </div>
    <div class="col-6">
      <%= f.text_field :unit_price, step: :any, class: 'form-control js-currency' %>
    </div>
  </div>

  <div class="col-12 text-center">
    <%= f.submit t('.add'), class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/orders/_product.html.erb
<tr id="<%= "product#{product.id}" %>">
  <th class="align-middle" scope="row"><%= product.id %></th>
  <th class="align-middle" scope="row"><%= product.name %></th>
  <th class="align-middle" scope="row"><%= product.multiple %></th>
  <th class="align-middle" scope="row"><%= number_to_currency(product.price) %></th>
  <th class="align-middle" scope="row"><%= text_field_tag("unit_price[#{product.id}]") %> </th>
  <th class="align-middle" scope="row"><%= number_field_tag("units[#{product.id}]") %></th>
</tr>

app/views/orders/edit.html.erb
<div class="row">
  <div class="col-10">
    <h2>
      <%= t('.title', id: @order.id) %>
    </h2>
  </div>
  <div class="col-2">
    <%= link_to root_path, class: 'btn btn-outline-primary' do %>
      <%= t('.back') %>
    <% end %>
  </div>
</div>

<hr class="line">

<%= form_for @order, url: order_path(@order.id), method: :patch do |f| %>
  <%= render(partial: 'form', locals: { order: @order, f: f }) %>

  <div class="col-12 text-center">
    <%= f.submit t('.save'), class: 'btn btn-primary' %>
  </div>
<% end %>

<hr class="line">

<%= render(partial: 'order_product_form', locals: { order: @order }) %>

<hr class="line">

<div class="row">
  <table class="table table-striped table-borderless">
    <thead>
      <tr class="align-middle">
        <th scope="col"></th>
        <th scope="col"><%= OrderProduct.human_attribute_name(:name) %></th>
        <th scope="col"><%= OrderProduct.human_attribute_name(:units) %></th>
        <th scope="col"><%= OrderProduct.human_attribute_name(:unit_price) %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= render(partial: 'order_product', collection: @order.order_products) %>
    </tbody>
  </table>
</div>

app/views/orders/index.html.erb
<div class="row">
  <div class="col-10">
    <h2>
      <%= Order.model_name.human(count: @orders.count) %>
    </h2>
  </div>
  <div class="col-2">
    <%= link_to new_order_path, class: 'btn btn-outline-primary' do %>
      <%= fa_icon('plus') %>
    <% end %>
  </div>
</div>

<hr class="line">

<div class="row">
  <table class="table table-striped table-borderless">
    <thead>
      <tr class="align-middle">
        <th scope="col">#</th>
        <th scope="col"><%= Order.human_attribute_name(:customer) %></th>
        <th scope="col"><%= OrderProduct.model_name.human(count: 2) %></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= render(partial: 'order', collection: @orders) %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-10">
    <h2>
      <%= t('.title') %>
    </h2>
  </div>
  <div class="col-2">
    <%= link_to root_path, class: 'btn btn-outline-primary' do %>
      <%= t('.back') %>
    <% end %>
  </div>
</div>

<hr class="line">

<%= form_for @new_order, url: orders_path, method: :post do |f| %>
  <%= render(partial: 'form', locals: { order: @new_order, f: f }) %>

  <div class="col-12 text-center">
    <%= f.submit t('.create'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="alert alert-<%= key %> btn-block" align="center">
      <%= value %>
    </div>
  </div>
<% end %>